name: Deploy to Firebase Hosting and Functions
on:
    push:
        branches:
            - dev

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm install

            - name: Install Firebase CLI
              run: npm install -g firebase-tools

            - name: Build the project
              env:
                  SIMPLE_APP_FIREBASE_PROJECT_ID: ${{ vars.SIMPLE_APP_FIREBASE_PROJECT_ID }}
                  SIMPLE_APP_FIREBASE_API_KEY: ${{ vars.SIMPLE_APP_FIREBASE_API_KEY }}
                  SIMPLE_APP_FIREBASE_AUTH_DOMAIN: ${{ vars.SIMPLE_APP_FIREBASE_AUTH_DOMAIN }}
                  SIMPLE_APP_FIREBASE_STORAGE_BUCKET: ${{ vars.SIMPLE_APP_FIREBASE_STORAGE_BUCKET }}
                  SIMPLE_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.SIMPLE_APP_FIREBASE_MESSAGING_SENDER_ID }}
                  SIMPLE_APP_FIREBASE_APP_ID: ${{ vars.SIMPLE_APP_FIREBASE_APP_ID}}
                  SIMPLE_APP_FIREBASE_MEASUREMENT_ID: ${{ vars.SIMPLE_APP_FIREBASE_MEASUREMENT_ID }}
                  SIMPLE_APP_FIREBASE_DATABASE_URL: ${{ vars.SIMPLE_APP_FIREBASE_DATABASE_URL }}
                  SIMPLE_APP_FIREBASE_FUNCTIONS_REGION: ${{ vars.SIMPLE_APP_FIREBASE_FUNCTIONS_REGION }}
              run: CI=false npm run build
            #      - name: Authenticate to FFirebase 1//053e_LU5QpzmDCgYIARAAGAUSNwF-L9Ir6VXQvtkKQwIuMc3EuOJtvEvdPcW3SwU-pgmzuNy7_Q4DVZlR6pN0Msb3oGCFLXXnrwg

            - name: Deploy to Firebase
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  SIMPLE_APP_FIREBASE_PROJECT_ID: ${{ vars.SIMPLE_APP_FIREBASE_PROJECT_ID }}
              run: firebase deploy --only hosting --token ${{ secrets.FIREBASE_TOKEN }} --project ${{ vars.SIMPLE_APP_FIREBASE_PROJECT_ID }}
